FROM node:22-slim
WORKDIR /app
COPY package.json package-lock.json* ./
COPY server/package.json server/package.json
COPY server/prisma server/prisma
COPY web/package.json web/package.json
RUN npm ci
COPY . .
